export const DRAW_CHART = 'DRAW_CHART'
export const SET_TITLE = 'SET_TITLE'
export const SET_JSON = 'SET_JSON'
export const SET_ENGINE = 'SET_ENGINE'
export const INITIAL = 'INITIAL'
export const SET_GENRE = 'SET_GENRE'
export const CHANGE_PALETTE = 'CHANGE_PALETTE'
